### ISSUE TITLE
porque setInterval ali? 

### ISSUE THREAD

**Issue by mauricionr** [joaocarlosalves/simple-localstorage#1]
https://github.com/joaocarlosalves/simple-localstorage/blob/5c96adb44bb3cd4967625dfc19174b68a4fa2d30/tls.js#L11

**Comment by joaocarlosalves** [comment]
Oi Mauricio, deixei pensando em alguem que possa querer algum tipo de retorno. 
Aceito dicas e sugestões :)

**Comment by joaocarlosalves** [comment]
Inclusive já tirei. XD

**Comment by mauricionr** [comment]
> Oi Mauricio, deixei pensando em alguem que possa querer algum tipo de retorno.
> Aceito dicas e sugestões :)

acho que quanto simples melhor e acho que o retorno que esta atualmente ja basta, mas posso estar enganado

**Comment by mauricionr** [comment]
ou talves retornar um `Promise.resolve` caso a operacao no `localStorage` aconteca sem erros 🤔

**Comment by joaocarlosalves** [comment]
gostei dessa ideia, da promise, farei um teste.
obrigado!
